#!/bin/bash
#
if [ "$(uname -o)" != "Android" ];then
	echo "Warning!对于linux的支持于2023.4.8终止"
	echo "退出安装"
	exit 1
fi

if [ -d .ntool ];then
	echo "看起来你似乎已经安装过ntool了"
	echo "你确定要安装/升级吗？"
	read -p "按回车继续"
fi

clear

printf "please wait...\n"

for i in git wget curl python dialog bc jq gawk;do
    if [ ! $(command -v ${i}) ];then
        pkg install -y ${i}
    fi
done
if [ "${*}" == "-n" ];then
    echo "从unstable安装,不从release"
    echo "please wait..."
    wget https://raw.githubusercontent.com/nnyyaa/ntool/main/ntool-termux
    mv ntool-termux ${PREFIX}/bin/ntool
    chmod +x ${PREFIX}/bin/ntool
    echo -e "完成"
    exit 0
fi
clear
printf "d8b   db d888888b  .d88b.   .d88b.  db\n"
printf "888o  88 '~~88~~' .8P  Y8. .8P  Y8. 88\n"
printf "88V8o 88    88    88    88 88    88 88\n"
printf "88 V8o88    88    88    88 88    88 88\n"
printf "88  V888    88    '8b  d8' '8b  d8' 88booo.\n"
printf "VP   V8P    YP     'Y88P'   'Y88P'  Y88888P\n"
sleep 0.2
printf "By Nya(https://github.com/nya-main/ntool)\n\n\n"

while true
do
read -p "你确定要执行这个脚本吗？  [Y|N]" answer
case $answer in
	Y|y)
		rm ~/.ntool/local_version > /dev/null 2>&1
        if [ "$(uname -o)" == "Android" ];then
	        wget https://raw.githubusercontent.com/nya-main/ntool/main/ntsource -O ${PREFIX}/bin/ntsource
            chmod +x ${PREFIX}/bin/ntool
		fi
	    wget https://raw.githubusercontent.com/nnyyaa/ntool/main/version -O ~/.ntool/local_version > /dev/null 2>&1
        cat > $PREFIX/bin/ntool <- EOF
        #there is nothing in this file.
        #all scripts are all in this file:$PREFIX/bin/ntsource
        #so this is just an start script
        #:D
        start $*
        EOF
    	echo "完成"
        echo "输入ntool测试启动"
		break
		;;
	N|n)
		echo "exiting..."
		break
		;;
	*)
		echo "未知的输入:\"$answer\"请确认输入无误"
		;;
esac
done
exit 0
