#!/data/data/com.termux/files/usr/bin/bash

if [ "$(uname -o)" != "Android" ];then
	echo "Warning!对于linux的支持于2023.4.8终止"
	echo "退出安装"
	exit 1
fi

if [ -d .ntool ];then
	echo "看起来你似乎已经安装过ntool了"
	echo "你确定要安装/升级吗？"
	read -p "按回车继续"
fi

clear

printf "please wait...\n"

for i in git wget curl python dialog bc jq gawk;do
    if [ ! $(command -v ${i}) ];then
        pkg install -y ${i}
    fi
done

clear
printf "d8b   db d888888b  .d88b.   .d88b.  db\n"
printf "888o  88 '~~88~~' .8P  Y8. .8P  Y8. 88\n"
printf "88V8o 88    88    88    88 88    88 88\n"
printf "88 V8o88    88    88    88 88    88 88\n"
printf "88  V888    88    '8b  d8' '8b  d8' 88booo.\n"
printf "VP   V8P    YP     'Y88P'   'Y88P'  Y88888P\n"
sleep 0.2
printf "By Nya(https://github.com/nya-main/ntool)\n\n\n"

function add_starter(){
cat << 'EOF' > $PREFIX/bin/ntool
#!/data/data/com.termux/files/usr/bin/bash
#there is nothing in this file.
#all scripts are all in this file:
#/data/data/com.termux/files/usr/lib/ntool/ntsf
#so this is just an start script
#:D
source /data/data/com.termux/files/usr/lib/ntool/ntsf
start $*
EOF
}

while true
do
read -p "你确定要执行这个脚本吗？  [Y|N]" answer
case $answer in
	Y|y)
		rm ~/.ntool/local_version > /dev/null 2>&1
        if [ "$(uname -o)" == "Android" ];then
            mkdir ${PREFIX}/lib/ntool
	        wget https://raw.githubusercontent.com/nya-main/ntool/main/ntsource -O ${PREFIX}/lib/ntool/ntsf
            add_starter
	        wget https://raw.githubusercontent.com/nnyyaa/ntool/main/version -O ~/.ntool/local_version > /dev/null 2>&1
        	echo "完成"
            echo "输入ntool测试启动"
        else
            echo "你未在Android或termux环境中执行脚本."
            exit 1
        fi
		break
		;;
	N|n)
		echo "exiting..."
		break
		;;
	*)
		echo "未知的输入:\"$answer\"请确认输入无误"
		;;
esac
done
exit 0
