#!/bin/bash
#####################
#  屎  山  代  码   #
#####################
#https://github.com/nya-main/ntool
#这也(一)许(定)后会成为一个烂尾工程吧
#chroot不会写(也许)(大概)(心虚)
#嗯只要没有人催我就不写a_@

function other_tool_tui(){			#这里是其他功能页的function
    OTPC=$(dialog --output-fd 1 --title "ntool-tui:other tool tui" --menu "选择一个以继续" 15 70 8 \
    "1" "网络页面" \
    "2" "工具页面" \
    "0" "返回上一页")
    EXITSTATUS=$?
    if [ $EXITSTATUS != 0 ];then
        termux_main_tui
    fi
    case $OTPC in 
        0)
		    termux_main_tui
            ;;
        1)
            web_tui
            ;;
	    2)
	    	tool_tui
		    ;;
    esac
}

function ssh_check_install(){
	if command -v ssh;then
		dialog --title "ntool-tui:ssh check" --msgbox "ssh功能较少,BUG多多,慎用" 15 70
		ssh_tui
	else
		echo "${RED}未安装ssh客户/服务端${RESET}"
		echo "${GREEN}安装中...${RESET}"
		pkg install -y openssh
        echo -e "${GREEN}"
        echo "完成"
        read -p "按任意键以继续"
        echo -e "${RESET}"
		ssh_check_install
	fi
}

function ssh_tui(){
    SSH_CHOICE=$(dialog --output-fd 1 --title "ntool-tui:ssh tui" --menu "选择一个以继续" 15 70 8 \
    "1" "打开sshd服务(让他人连接)" \
    "2" "通过密码连接远程服务器" \
    "3" "生成密钥" \
    "0" "返回上一页")
    EXITSTATUS=$?
    if [ $EXITSTATUS != 0 ];then
        tool_tui
    fi
	case $SSH_CHOICE in
		0)
			tool_tui
			;;
		1)
			sshd
            echo -e "${GREEN}"
			read -p "启动完成 按任意键继续"
            echo -e "${RESET}"
			exit 0
			;;
		2)
			if command -v sshpass;then
				read -p "输入远程服务器ip/域名:" ssh_ip
				read -p "输入要登陆的用户名:" ssh_user
				read -p "输入ssh端口:" ssh_port
				read -p "输入密码:" ssh_passwd
				echo "please wait..."
				sshpass -p ${ssh_passwd} ssh ${ssh_user}@${ssh_ip} -p ${ssh_port}
			else
				echo "sshpass未安装"
				echo "installing..."
                pkg install -y sshpass
				ssh_tui
			fi
			;;
		3)
            while true;
            do
            EMAILINPUT=$(dialog --output-fd 1 --title "ntool-tui:keygen" --inputbox "使用RSA\n输入你的邮箱:" 15 70)
            EXITSTATUS=$?
            if [ -a EMAILINPUT  ];then
                bad_empty_input
            elif [ $EXITSTATUS != 0 ];then
                ssh_tui
                break
            else
                break
            fi
            done
            echo -e "${GREEN}接下来请一路回车${RESET}"
            ssh-keygen -t rsa -C "$EmailInput"
            echo -e "${GREEN}完成!\n公钥在:${HOME}/.ssh/id_rsa.pub\n私钥在:${HOME}/.ssh/id_rsa"
            read -p "按任意键继续"
			;;
	esac
}

function tool_tui(){			#这里是其它工具-工具类页面的function
    TPC=$(dialog --output-fd 1 --title "ntool-tui:tool tui" --menu "选择一个以继续" 15 70 8 \
    "1" "ping" \
    "2" "ping6" \
    "3" "文件查找" \
    "4" "安装openjdk17" \
    "5" "ssh功能" \
    "6" "二维码功能" \
    "7" "rm防误删" \
    "00" "打开该项目地址(?)" \
    "0" "返回上一页")
    EXITSTATUS=$?
    if [ $EXITSTATUS != 0 ];then
        other_tool_tui
    fi
	case $TPC in
		0)
			other_tool_tui
			;;
		00)
            print_author NTool nya
			am start -a android.intent.action.VIEW -d ${GHREPO} > /dev/null 2>&1
			;;

		1)
			if command -v ping > /dev/null 2>&1;then
                 ip=$(dialog --output-fd 1 --title "ntool-tui:ping-ip" --inputbox "输入要进行ping的IP/域名(必填)"15 70)
                 time=$(dialog --output-fd 1 --title "ntool-tui:ping-time" --inputbox "输入要ping的次数(选填)" 15 70)
                 speed=$(dialog --output-fd 1 --title "ntool-tui:ping-speed" --inputbox "输入ping的速度(选填)（以秒为单位，省略符号，无root最快0.2）" 15 70)
                 size=$(dialog --output-fd 1 --title "ntool-tui:ping-packet-szie" --inputbox "输入ping包大小(选填)(以字节为单位，最大65507)" 15 70)
                if [ -z $ip ] || [ -z $time ] || [ -z $speed ] || [ -z $size ];then
                    bad_empty_input
                    tool_tui
                else 
                    echo -e "${BLUE}start ping${RESET}"
    				ping -i ${speed} -c${times} -s ${size} ${ip}
	    			echo -e "${GREEN}stop ping${RESET}"
                fi
			else
				echo "未安装ping，正在安装..."
				pkg install -y termux-tools
				tool_tui
			fi
			;;
		2)
			if command -v ping6 > /dev/null;then
                 ip=$(dialog --output-fd 1 --title "ntool-tui:ping6-ip" --inputbox "输入要进行ping6的IP/域名(必填)"15 70)
                 time=$(dialog --output-fd 1 --title "ntool-tui:ping6-time" --inputbox "输入要ping6的次数(选填)" 15 70)
                 speed=$(dialog --output-fd 1 --title "ntool-tui:ping6-speed" --inputbox "输入ping6的速度(选填)（以秒为单位，省略符号，无root最快0.2）" 15 70)
                 size=$(dialog --output-fd 1 --title "ntool-tui:ping6-packet-szie" --inputbox "输入ping6包大小(选填)(以字节为单位，最大65507)" 15 70)
                if [ -z $ip ] || [ -z $time ] || [ -z $speed ] || [ -z $size ];then
                    bad_empty_input
                    tool_tui
                else
                    echo -e "${BLUE}start ping${RESET}"
                    ping6 -i ${speed} -c${time} -s ${size} ${ip}
                    echo -e "${GREEN}stop ping${RESET}"
                fi
			else
				echo "ping6未安装,正在安装..."
				pkg install -y termux-tools
				tool_tui
			fi
			;;
		3)
             filename=$(dialog --output-fd 1 --title "ntool-tui:find file" --inputbox "输入你要搜索的文件:" 15 70)
             filepath=$(dialog --output-fd 1 --title "ntool-tui:find file" --inputbox "输入你要搜索的目录:" 15 70)
            if [ -z $filename ] || [ -z $filepath ];then
                bad_empty_input
            fi
			echo -e "${BLUE}搜索中${RESET}"
            echo -e "可能${RED}较慢${RESET},请${GREEN}耐心等待${RESET}"
            echo -e "${BLUE}搜索中${RESET}"
            result=$(find -name ${filename} ${filepath})
            echo "${result}" > ~/filesearchresult
            echo -e "${GREEN}完成${RESET}"
            echo -e "${BLUE}结果:${RESET}\n${result}"
            echo -e "${GREEN}复制一份于~/filesearchresult"
            read -p "按回车继续"
            echo -e "$RESET"
            tool_tui
			;;
		4)
			echo "只支持openjdk17"
			read -p "按任意键以继续"	#我好水啊（）
			pkg install -y openjdk-17
			echo "安装完成"
			;;
		5)
            source "${NTOOLLIB}/basic/ssh.sh"
			ssh_check_install
			;;
		6)
            source "${NTOOLLIB}/basic/qrcode.sh"
            command -v qrencode 
            EXITSTATUS=$?
            if [ ${EXITSTATUS} != 0 ];then
                pkg install -y libqrencode zbar
                qrcode_tui
            else
                qrcode_tui
            fi
			;;
        7)
            source "${NTOOLLIB}/basic/trashbin.sh"
            rm_to_trash
            ;;
	esac
    exit 0
}

function web_tui(){				#这里是其他功能-网络类页面function
	#echo "这里是最水的页面（doge）"
    webc=$(dialog --output-fd 1 --title "ntool-tui:web tui" --menu "选择一个以继续" 15 70 8 \
    "1" "安装Nginx" \
    "2" "安装Apache2" \
    "3" "安装php环境" \
    "4" "安装MySQL(mariadb)" \
    "0" "返回上一页")
    EXITSTATUS=$?
	if [ $EXITSTATUS != 0 ];then
        other_tool_tui
    fi
	case $webc in
		0)
			other_tool_tui
			;;
		1)
			pkg install -y nginx
			echo "done"
			;;
		2)
			pkg install -y apache2
			echo "done"
			;;
		3)
			pkg install -y php
			echo "done"
			;;
		4)
			pkg install -y mariadb
			echo "done"
			;;
	esac
}

######main tui
function termux_main_tui(){
    MAINCHOICE=$(dialog --output-fd 1 --title "ntool-tui:main tui" --menu "你的系统为:${OS}\n选择一个以继续" 15 70 8  \
    "1" "已烂尾的容器功能" \
    "2" "其它功能" \
    "3" "备份功能" \
    "4" "计算圆周率(好水)" \
    "5" "一言" \
    "6" "LSPatch/XPatch功能" \
    "7" "ntafetch-使用ntafetch作为motd(测试)" \
    "8" "反映一个BUG" \
    "9" "卸载 ntool" \
    "10" "一些好用的东西" \
    "00" "更新" \
    "0" "退出")
    EXITSTATUS=$?
    if [ $EXITSTATUS != 0 ];then
        echo -e "${BLUE}b${GREEN}y${YELLOW}e${RESET}"
        exit 0
    fi
    case $MAINCHOICE in 
        00)
	        check_and_update
        	;;
        0)
            echo -e "${BLUE}b${GREEN}y${YELLOW}e${RESET}"
            exit 0
            ;;
        1)
            source "${NTOOLLIB}/container/container.sh"
            container_tui
            ;;
        2)
            other_tool_tui
            ;;
        3)
            source "${NTOOLLIB}/basic/backup.sh"
            backup_tui
            ;;
        4)
            if command -v bc > /dev/null;then
                 BC=$(dialog --output-fd 1 --title "ntool-tui:bc PI" --inputbox "输入计算位数    越往后面算的越慢" 15 70)
                EXITSTATUS=$?
                if [ $EXITSTATUS != 0 ];then
                    termux_main_tui
                fi
                echo -e "${GREEN}请耐心等待...${RESET}"
                echo "计算开始时间:$(date '+%Y-%m-%d %H:%M:%S.%N')" > ${HOME}/pi.txt
                echo "scale=${BC}; 4*a(1)" | bc -l -q >> ${HOME}/pi.txt
                echo "计算结束时间:$(date '+%Y-%m-%d %H:%M:%S.%N')" >> ${HOME}/pi.txt
                dialog --title "ntool-tui:success" --textbox "${HOME}/pi.txt" 20 80
                termux_main_tui
            else
                echo -e "${BLUE}正在安装bc计算器...${RESET}"
                pkg install -y bc
                echo -e ${GREEN}
                read -p "按回车返回"
                echo -e ${RESET}
                termux_main_tui
            fi
            ;;
        5)
            dialog --title "ntool-一言" --msgbox "$(curl https://v1.hitokoto.cn/?encode=text 2>/dev/null)" 15 70
            termux_main_tui
            ;;
        6)
            source "${NTOOLLIB}/basic/lsxpatch.sh"
            patch_framework_choose
            ;;
        7)
            check_if_not_android_warning
            function ntafetch_install(){
                wget https://raw.githubusercontent.com/nya-main/ntafetch/main/ntafetch -O ${PREFIX}/bin/ntafetch
                chmod +x ${PREFIX}/bin/ntafetch
                mv $PREFIX/etc/motd ${PREFIX}/etc/motd.bak > /dev/null 2>&1
            }
            if (dialog --title "ntool-tui:developing action" --defaultno --yesno "ntafetch由无数个echo -e组成\n写这个的主要原因是因为termux自带motd过于臃肿\n并不推荐使用，因为没有经过足够的测试" 15 70);then
                 ISINSTALLED="$(cat ${PREFIX}/etc/termux-login.sh | grep ntafetch)"
                if [ ! -z "$ISINSTALLED" ];then
                    if (dialog --title "ntool-tui:WARNING" --defaultno --yesno "你已经安装过ntafetch了\n你确定要重装吗?" 15 70);then
                        ntafetch_install
                    else
                        termux_main_tui
                    fi
                else
                    ntafetch_install
                    echo "ntafetch" >> ${PREFIX}/etc/termux-login.sh
                fi
            else
                termux_main_tui
            fi
            termux_main_tui
            ;;
        8)
            dialog --title "ntool-tui:report" --yes-label "GitHub" --no-label "Blog" --yesno "你可以到ntool项目下提出issue \n或者到博客的关于页找我 \n我也会看的" 15 70
            EXITSTATUS=$?
            if [ ${EXITSTATUS} = 255 ];then
                termux_main_tui
            elif [ ${EXITSTATUS} = 0 ];then
                am start -a android.intent.action.VIEW -d ${GHREPO} > /dev/null 2>&1
            elif [ ${EXITSTATUS} = 1 ];then
                dialog --title "ntool-tui:give me the money!" --yes-label "好的" --no-label "可以" --yesno "博客由于经营不善,倒闭了qwq\n我需要你的帮助(⁠≧⁠▽⁠≦⁠)\n你愿意v我50嘛?" 0 0
                EXITSTATUS=$?
                if [ ${EXITSTATUS} = 255 ];then
                    echo -e "哼,连50都不愿意给我!!\n再也不见qwq"
                    exit 123
                else
                    echo -e "${CYAN}好耶!${RESET}"
                    read -p "press enter please"
                    termux_main_tui
                fi
            fi
            ;;
        9)
            source "${NTOOLLIB}/basic/uninstall.sh"
            uninstall_ntool
            ;;
        10)
            source "${NTOOLLIB}/other/other_main.sh"
            other_main_tui
            ;;
    esac
    exit 0
}
