#!/data/data/com.termux/files/usr/bin/env bash
####################
#                  #
#  屎  山  代  码  #
#                  #
####################
#也许你不知道，但是我在2022你才刚高一
#在高一时的我属于是真正的大屎山代码创造者
#(虽然现在也还是)
#代码虽然是自己敲的
#但是真的好jb的乱
#也许这以后会成为一个烂尾工程吧(确信)

arch="`uname -m`"

update()
{
	cd ~
	wget https://raw.githubusercontent.com/nnyyaa/ntool/main/install.sh
	chmod +x ~/install.sh
	~/install.sh
}
chooseos()
{
	echo "0. 退出"
	echo "1. Ubuntu"
	echo "2. debian"
	read -p "输入你的选择:" cos
	case $cos in
                1)
			cd ~/.ntool
                        if [ ! -a "ub-i.sh" ];
			then
				chmod +x ub-i.sh
				./ub-i.sh
			else
				wget https://raw.githubusercontent.com/nnyyaa/ntool/main/sc/ub-i.sh
				chmod +x ub-i.sh
				./ub-i.sh
			fi
                        ;;
		2)
			cd ~/.ntool
			if [ ! -a "de-i.sh" ];
			then
				chmod +x de-i.sh
				./de-i.sh
			else wget https://raw.githubusercontent.com/nnyyaa/ntool/main/sc/de-i.sh
				chmod +x de-i.sh
				./de-i.sh
			fi
			exit 0
			;;
                *)
                        echo "未知选项"
			exit 0
                        ;;
	esac
}

while true
do
clear
neofetch
echo "当前版本:v0.0.2"
echo "你的架构为:${arch}"
echo "1. 安装一个proot容器"
echo "0. 退出"
echo "00. 升级脚本"
read -p "输入你的选择:" choice
case $choice in
	0)
		echo "退出"
		break
		;;
	1)
		chooseos
		break
		;;
	00)
		update
		break
		;;
	*)
		echo "输入一个没有的选项是在为难我嘛！"
		sleep 3
		;;

esac
done
echo "完成运行  退出"
exit 0
