#!/data/data/com.termux/files/usr/bin/env bash
####################
#                  #
#  屎  山  代  码  #
#                  #
####################
#也许你不知道，但是我在2022你才刚高一
#在高一时的我属于是真正的大屎山代码创造者
#(虽然现在也还是)
#代码虽然是自己敲的
#但是真的好jb的乱
#也许这以后会成为一个烂尾工程吧(确信)

arch="`uname -m`"

update()
{
	cd ~
	wget https://raw.githubusercontent.com/nnyyaa/ntool/main/install.sh
	chmod +x ~/install.sh
	~/install.sh
}
chooseos()
{
	echo "0. 退出"
	echo "1. Ubuntu"
	echo "2. debian"
	read -p "输入你的选择:" cos
	case $cos in
                1)
                        ubinstall
                        ;;
		2)
			deinstall
			exit 0
			;;
                *)
                        echo "未知选项"
			exit 0
                        ;;
	esac
}
ubinstall()
{
	if [ -d "~/.ntool/ubuntu-fs" ];
	then
		echo "看起来你可能安装过了"
		echo "重复安装会导致错误"
		echo "故终止该脚本运行"
		echo "如果需重新安装"
		echo "请手动执行: rm -rf ~/.ntool/ubuntu-fs $PREFIX/startubuntu"
		exit 0
	else
		echo "请花一点时间，到百度搜索一下你所要安装的ubuntu的版本号"
		echo "输错将导致安装失败!"
		echo "推荐lts版本:22.04"
		read -p "请输入正确的版本号(数字)!:" version
		cd ~
		apt update
		apt upgrade
		apt install git tar zip unzip wget curl -y
		sleep 2
		echo "请耐心等待......"
		wget https://mirrors.bfsu.edu.cn/ubuntu-cdimage/ubuntu-base/releases/${version}/release/ubuntu-base-${version}-base-arm64.tar.gz
		mkdir -p ~/.ntool/ubuntu-fs
		mv ubuntu-base-${version}-base-arm64.tar.gz ~/.ntool/ubuntu-fs
		cd ~/.ntool/ubuntu-fs
		tar -xvzf ubuntu-base-${version}-base-arm64.tar.gz
		cd ~
		cd ubuntu-fs/etc
		wget https://raw.githubusercontent.com/nnyyaa/ubuntu-on-droid/main/resolv.conf
		wget -O sources.list https://raw.githubusercontent.com/nnyyaa/ntool/main/sources-${version}.list
		cd ~
		wget https://raw.githubusercontent.com/nnyyaa/ntool/main/startubuntu
		mv sources.list ./apt/
		chmod +x startubuntu
		mv ~/startubuntu $PREFIX/bin
		echo "完成！"
		echo "输入 "startubuntu" 来启动"
	fi
}
deinstall()
{
	echo "等待开发..."
}

cd ~
while true
do
clear
neofetch
echo "当前版本:v0.0.2"
echo "你的架构为:${arch}"
echo "1. 安装一个proot容器"
echo "0. 退出"
echo "00. 升级脚本"
read -p "输入你的选择:" choice
case $choice in
	0)
		echo "退出"
		break
		;;
	1)
		chooseos
		break
		;;
	00)
		update
		break
		;;
	*)
		echo "输入一个没有的选项是在为难我嘛！"
		sleep 3
		;;

esac
done
echo "完成运行  退出"
exit 0
