#!/bin/bash
RED="\E[1;31m"
GREEN="\E[1;32m"
YELLOW="\E[1;33m"
BLUE="\E[1;34m"
PINK="\E[1;35m"
CYAN="\e[36m"
RESET="\E[0m"
RNTOOL="${RED}n${YELLOW}t${BLUE}o${PINK}o${CYAN}l${RESET}"
########预准备
ARCH="$(uname -m)"
TIME=$(date '+%Y-%m-%d %H:%M:%S')
if [ "$ARCH" == "aarch64" ];then
    ARCH="arm64"
fi
OS="$(cat /etc/os-release | gawk 'NR==2' | gawk -F '"' '{print $2}')"     #系统
if [[ "${OS}" != "Ubuntu" && "Debian" ]];then
    dialog --title "ntool-tui:WARNING" --msgbox "未适配的linux发行版:${OS}" 15 70
    exit 0
fi
STORAGEPATH="/storage/emulated/0/Download/backup"       #备份及rootfs下载目录
MAINPATH="${HOME}/.ntool"      #主目录
RAWURL="https://raw.githubusercontent.com/nnyyaa/ntool/main"       #GitHub raw地址(我是一只懒懒的猫猫)

if [ "${ARCH}" != "arm64" ];then
    dialog --title "ntool-tui:WARNING" --msgbox "你的架构是${ARCH}而不是arm64/aarch64\n通常来说这会造成问题,但是我已竭力适配不同的架构了\n你可以测试一下" 15 70
elif [ "${OS}" == "Android" ];then
    dialog --title "ntool-tui:WARNING" --msgbox "该版本不适配Android..." 15 70
    exit 1
fi
###以下部分目的为获取包管理器
for i in pacman apt yum;do
    if [ $(command -v ${i}) ];then
        PKG=$i
    fi
done
case $PKG in
    apt)
        PKGI="apt install -y"
        PKGUNI="apt purge -y"
        PKGUPD="apt update"
        PKGUPG="apt upgrade -y"
        PKGUP="${PKGUPD} && ${PKGUPG}"
        ;;
    pacman)
        PKGI="pacman -S"
        PKGUNI="pacman -R"
        PKGUPD="pacman -Syy"
        ;;
    yum)
        PKGI="yum install -y"
        PKGUNI="yum remove"
        PKGUPD="yum update && yum upgrade -y"
        ;;
    *)
        dialog --title "ntool-tui:WARNING" --msgbox "未知的包管理器" 15 70
        exit 0
        ;;
esac
###常用function
function wait_for_dev_tui(){
    dialog --title "ntool-tui:developing tui" --msgbox "正在开发" 15 70
    exit 1
}
function bad_empty_input(){
    dialog --title "ntool-tui:WARNING" --msgbox "严重错误:不允许的空选项" 15 70
    return 1
}
#################
function change_source(){
    MIRRORSITE=$(dialog --output-fd 1 --title "ntool-tui:change source" --menu "选择一个镜像站:" 15 70 8 \
    "mirrors.bfsu.edu.cn" "BFSU 广度搜索大学(划掉)北京外国语大学镜像站" \
    "mirrors.tuna.tsinghua.edu.cn" "TUNA 清华大学镜像站")
    case ${OS} in
        Ubuntu|ubuntu)
            if [[ "${ARCH}" == "amd64" || "i386" ]];then
                sed -i "s/archive.ubuntu.com/${MIRRORSITE}/" /etc/apt/sources.list
            else
                sed -i "s/ports.ubuntu.com/${MIRRORSITE}/" /etc/apt/sources.list
            fi
            ${PKGUP}
            dialog --title "ntool-tui:success" --msgbox "完成!" 15 70
            ;;
        Debian|debian)
            sed -i "s/deb.debian.org//${MIRRORSITE}/" /etc/apt/sources.list
            ${PKGUP}
            ;;
    esac
}



MAINCHOICE=$(dialog --output-fd 1 --title "ntool-tui:main tui" --menu "你在使用linux版\n选择一个以继续" 17 70 8 \
"1" "安装奇妙的软件" \
"2" "换源")
case ${MAINCHOICE} in
    1)
        wait_for_dev_tui
        package_installer
        ;;
    2)
        change_source
        ;;
esac
echo "bye"
exit 0
