#!/bin/bash
#####################
#  屎  山  代  码   #
#####################
#https://github.com/nya-main/ntool
#这也(一)许(定)后会成为一个烂尾工程吧
#chroot不会写(也许)(大概)(心虚)
#嗯只要没有人催我就不写a_@

function patch_framework_choose(){
    if (dialog --title "ntool-tui:WARNING" --yesno "你在使用一个测试功能\n 你确定要继续吗" 15 70);then
        EXITSTATUS=$?
        if [ $EXITSTATUS != 0 ];then
            termux_main_tui
        fi
        dialog --title "ntool-tui:选择patch框架" --yes-label "XPatch" --no-label "LSPatch" --yesno "基于Java，选择任何一个选项都将安装OpenJdk17\n本页面用于免root使用lsp或xp注入应用\nLSPatch的应用仅支持安卓9及以上但较为稳定\nXPatch则是几乎全版本支持但稳定性不好,支持的模块也大大少于LSPatch\n两种patch方式都很像无极" 15 70
        EXITSTATUS=$?
        case ${EXITSTATUS} in
            0)
                PATCHFRAMEWORK=xpatch
                ;;
            1)
                PATCHFRAMEWORK=lspatch
                ;;
        esac
        if command -v java jq > /dev/null 2>&1;then
            patch_apk
        else
            pkg install -y openjdk-17 jq
            patch_apk
        fi
    else
        termux_main_tui
    fi
}

function patch_apk(){
    APKPATH=$(dialog --output-fd 1 --title "ntool-tui:fast ${PATCHFRAMEWORK}" --inputbox "输入apk完整路径\n 不是apk文件的上一级目录!!!" 15 70)
    EXITSTATUS=$?
    if [ $EXITSTATUS != 0 ];then
        patch_framework_choose
    elif [ -z $APKPATH ];then
        bad_empty_input
        patch_apk
    fi
    mkdir -p ${MAINPATH}/patch
    case ${PATCHFRAMEWORK} in
        xpatch)
            echo -e "${BLUE}获取最新版本号中${RESET}"
            TAG=$(wget -qO- -t1 -T2 "https://api.github.com/repos/WindySha/Xpatch/releases/latest" | jq -r '.tag_name')
            echo -e "${GREEN}${PATCHFRAME}最新版为${TAG}${RESET}"
            wget https://github.com/WindySha/Xpatch/releases/download/${TAG}/xpatch-${tag}.jar -O ${MAINPATH}/patch/xpatch.jar
            ;;
        lspatch)
            TAG=$(wget -qO- -t1 -T2 "https://api.github.com/repos/LSPosed/LSPatch/releases/latest" | jq -r '.tag_name')
            echo -e "${GREEN}${PATCHFRAME}最新版为${TAG}${RESET}"
            wget https://github.com/LSPosed/LSPatch/releases/download/${TAG}/lspatch.jar -O ${MAINPATH}/patch/lspatch.jar
            ;;
    esac
    if [ ! -f ${APKPATH} ];then
        dialog --title "ntool-tui:failed" --msgbox "无效的apk文件路径\n 检查是否输入错误或有无给予内置存储权限" 15 70
        patch_apk
    fi
    MODULEPATH=$(dialog --output-fd 1 --title "ntool-tui:选择模块" --inputbox "输入模块apk的完整路径\n 不是apk文件的上一级目录!!!" 15 70)
    echo -e "${BLUE}可能${RED}较慢${RESET},请${GREEN}耐心等待${RESET}"
    if [ "$PATCHFRAME" == "xpatch" ];then
        java -jar ${MAINPATH}/patchedapks/xpatch.jar ${APKPATH} -xm ${MODULEPATH} -o /sdcard/xpatchedapk.apk
        rm ${MAINPATH}/patchedapks/xpatch.jar
    else
        java -jar ${MAINPATH}/patchedapks/lspatch.jar ${APKPATH} -m ${MODULEPATH} -o /sdcard
        rm ${MAINPATH}/patchedapks/lspatch.jar
    fi
    echo -e "${GREEN}完成!修改后的apk${BLUE}在这里↑↑↑↑↑上面${RESET}"
    read -p "按回车继续"
    exit 0
}

function backup_tui(){      #备份页面function
    backup_tui_choice=$(dialog --output-fd 1 --title "ntool-tui:backup tui" --menu "选择一个以继续" 15 70 8 \
    "0" "返回脚本主页" \
    "1" "备份termux" \
    "2" "恢复备份" \
    "3" "删除备份" )
    EXITSTATUS=$?
    if [ $EXITSTATUS != 0 ];then
        termux_main_tui
    fi
    case $backup_tui_choice in
        0)
            termux_main_tui
            ;;
        1)
            BACKUP_NAME=$(dialog --output-fd 1 --title "ntool-tui:backup name" --inputbox "输入备份名(仅备份com.termux/files以提高速度) " 15 70)
            EXITSTATUS=$?
            if [ $EXITSTATUS != 0 ];then
                backup_tui
            elif  [ -z $BACKUP_NAME ];then
                bad_empty_input
                backup_tui
            fi
            cd ~
            if command -v tar > /dev/null;then
                if [ -d storage ];then
                    dialog --title "ntool-tui:tips" --msgbox "备份可能会很慢,请耐心等待" 15 70
                    cd /data/data/com.termux/
                    tar -cvpzf ${STORAGEPATH}/${BACKUP_NAME}.tgz files
                    echo -e "${GREEN}计算sha1...${RESET}"
                    sha1sum ${STORAGEPATH}/${BACKUP_NAME}.tgz > ${STORAGEPATH}/${BACKUP_NAME}.tgz.sha
                    echo -e "${GREEN}完成备份${RESET}"
                    read -p  "按任意键退出"
                    backup_tui
                else
                    echo -e "${RED}termux-setup-storage未执行${RESET}"
                    echo -e "${BLUE}执行中...${RESET}"
                    sleep 2
                    termux-setup-storage
                    echo "${GREEN}完成${RESET}"
                    backup_tui
                fi
            else
                echo "tar未安装"
                echo "start installing..."
                pkg install -y tar
                backup_tui
            fi
            ;;
        2)
            RESTORE_PATH=$(dialog --output-fd 1 --title "ntool-tui:输入完整目录！" --inputbox ${STORAGEPATH} 15 70)
            EXITSTATUS=$?
            if [ $EXITSTATUS != 0 ];then
                backup_tui
                exit 0
            elif [ -z $RESTORE_PATH ];then
                bad_empty_input
                backup_tui
            fi 
            cd ~
            echo "比对sha中..."
            sha1sum -c ${RESTORE_PATH}.sha >> /dev/null 2>&1
            EXITSTATUS=$?
            if [ $EXITSTATUS = 0 ];then 
                echo -e "${GREEN}sha正常${RESET}"
                echo "${GREEN}3${BLUE}秒后开始恢复${RESET}"
                sleep 3
                tar -xvpzf ${RESTORE_PATH} -C /data/data/com.termux/
                echo -e  "${GREEN}完成，重启生效，按回车以退出${RESET}"
            else
                dialog --title "ntool-tui:WARNING" --msgbox "警告:不匹配的sha值!不进行恢复" 15 70
                backup_tui 
            fi
            ;;
        3)
            DEL_BACKUP_PATH=$(dialog --output-fd 1 --title "ntool-tui:输入完整目录" --inputbox "输入完整tgz文件路径" 15 70)
            EXITSTATUS=$?
            if [ $EXITSTATUS != 0 ];then
                backup_tui
            elif [ -z $DEL_BACKUP_PATH ];then
                bad_empty_input
                backup_tui
            fi 
            rm -v ${DEL_BACKUP_PATH}
            rm -v ${DEL_BACKUP_PATH}.sha
            read -p "按任意键继续"
            backup_tui
            ;;
    esac
}

function other_tool_tui(){			#这里是其他功能页的function
    OTPC=$(dialog --output-fd 1 --title "ntool-tui:other tool tui" --menu "选择一个以继续" 15 70 8 \
    "1" "网络页面" \
    "2" "工具页面" \
    "0" "返回上一页")
    EXITSTATUS=$?
    if [ $EXITSTATUS != 0 ];then
        termux_main_tui
    fi
    case $OTPC in 
        0)
		    termux_main_tui
            ;;
        1)
            web_tui
            ;;
	    2)
	    	tool_tui
		    ;;
    esac
}

function ssh_check_install(){
	if command -v ssh;then
		dialog --title "ntool-tui:ssh check" --msgbox "ssh功能较少,BUG多多,慎用" 15 70
		ssh_tui
	else
		echo "${RED}未安装ssh客户/服务端${RESET}"
		echo "${GREEN}安装中...${RESET}"
		pkg install -y openssh
        echo -e "${GREEN}"
        echo "完成"
        read -p "按任意键以继续"
        echo -e "${RESET}"
		ssh_check_install
	fi
}

function ssh_tui(){
    SSH_CHOICE=$(dialog --output-fd 1 --title "ntool-tui:ssh tui" --menu "选择一个以继续" 15 70 8 \
    "1" "打开sshd服务(让他人连接)" \
    "2" "通过密码连接远程服务器" \
    "3" "生成密钥" \
    "0" "返回上一页")
    EXITSTATUS=$?
    if [ $EXITSTATUS != 0 ];then
        tool_tui
    fi
	case $SSH_CHOICE in
		0)
			tool_tui
			;;
		1)
			sshd
            echo -e "${GREEN}"
			read -p "启动完成 按任意键继续"
            echo -e "${RESET}"
			exit 0
			;;
		2)
			if command -v sshpass;then
				read -p "输入远程服务器ip/域名:" ssh_ip
				read -p "输入要登陆的用户名:" ssh_user
				read -p "输入ssh端口:" ssh_port
				read -p "输入密码:" ssh_passwd
				echo "please wait..."
				sshpass -p ${ssh_passwd} ssh ${ssh_user}@${ssh_ip} -p ${ssh_port}
			else
				echo "sshpass未安装"
				echo "installing..."
                pkg install -y sshpass
				ssh_tui
			fi
			;;
		3)
            while true;
            do
            EMAILINPUT=$(dialog --output-fd 1 --title "ntool-tui:keygen" --inputbox "使用RSA\n输入你的邮箱:" 15 70)
            EXITSTATUS=$?
            if [ -a EMAILINPUT  ];then
                bad_empty_input
            elif [ $EXITSTATUS != 0 ];then
                ssh_tui
                break
            else
                break
            fi
            done
            echo -e "${GREEN}接下来请一路回车${RESET}"
            ssh-keygen -t rsa -C "$EmailInput"
            echo -e "${GREEN}完成!\n公钥在:${HOME}/.ssh/id_rsa.pub\n私钥在:${HOME}/.ssh/id_rsa"
            read -p "按任意键继续"
			;;
	esac
}
function qrcode_tui(){
    QRCHOICE=$(dialog --output-fd 1 --title "ntool-tui:按<ESC>返回上一页" --yes-label "生成" --no-label "解码" --yesno "使用 \nqrencode 和 zbar实现 \n选择一个以继续" 15 70)
    EXITSTATUS=$?
    if [ ${EXITSTATUS} = 255 ];then
        tool_tui
    fi
    case ${EXITSTATUS} in
        0)
            QRSPAWN=$(dialog --output-fd 1 --title "ntool-tui:qrcode spawn" --inputbox "输入你想要加密的文本" 15 70)
            EXITSTATUS=$?
            if [ ${EXITSTATUS} != 0 ];then
                qrcode_tui
            fi
            dialog --output-fd 1 --title "ntool-tui:configure" --yesno "是否要保存该二维码到内置存储目录?" 15 70
            EXITSTATUS=$?
            if [ ${EXITSTATUS} != 0 ];then
                qrencode -o - -t ANSI "${QRSPAWN}"
                echo -e "${GREEN}"
                read -p "按回车继续"
                echo -e "${RESET}"
                qrcode_tui
            else
                QRSTOREPATH=$(dialog --output-fd 1 --title "按空格选择" --dselect "/sdcard" 15 70)
                EXITSTATUS=$?
                if [ ${EXITSTATUS} != 0 ];then
                    qrcode_tui
                elif [ -z ${QRSTOREPATH} ];then
                    bad_empty_input
                    qrcode_tui
                fi
                qrencode -t png -o ${QRSTOREPATH}/qrcode-${QRSPAWN}.png "${QRSPAWN}"
                catimg ${QRSTOREPATH}/qrcode-${QRSPAWN}.png
                echo -e "${GREEN}完成!保存在${BLUE}${QRSTOREPATH}/qrcode-${QRSPAWN}.png${RESET}"
                echo -e "${GREEN}"
                read -p "按回车继续"
                echo -e "${RESET}"
                qrcode_tui
            fi
            ;;
        1)
            QRUNCODEPATH=$(dialog --output-fd 1 --title "ntool-tui:qrcode uncode" --fselect "选择好文件后按空格选择(删掉我),或者直接输入完整路径" 15 70)
            EXITSTATUS=$?
            if [ -z ${QRUNCODEPATH} ];then
                bad_empty_input
                qrcode_tui
            elif [ ${EXITSTATUS} != 0 ];then
                qrcode_tui
            fi
            echo -e "${BLUE}结果${RESET}:$(zbarimg ${QRUNCODEPATH} | sed -n '1p')"
            echo -e "${GREEN}"
            read -p "按回车继续"
            echo -e "${RESET}"
            qrcode_tui
            ;;
    esac
}

function rm_to_trash(){
    dialog --title "ntool-tui:按ESC退出" --yes-label "trash-cli" --no-label "rm" --yesno "trash-cli是一个适用于linux命令行下的回收站应用\n相对于rm的直接删除它更为安全,因为可以恢复\n删除后的文件将被保存在回收站\n真的是我的血的教训" 15 70
    EXITSTATUS=$?
    if [ ${EXITSTATUS} = 255 ];then
        tool_tui
    fi
    case ${EXITSTATUS} in
        0)
            if [ $(cat ${PREFIX}/etc/profile | grep trash) ];then
                dialog --title "ntool-tui:tips" --msgbox "你已经安装过啦!下面是一些使用提示: \nrm-文件转移到~/.trash \nrl-显示回收站里的文件 \nrm-restore-选择要从回收站里恢复的文件 \ntrash-empty-清除回收站" 15 70
                exit 0
            else
                if [ ! $(command -v trash) ];then
                    pip install trash-cli
                fi
                cat >> ${PREFIX}/etc/profile << EOF
alias rm='trash-put --trash-dir ~/.trash'
alias rl='trash-list --trash-dir ~/.trash'
alias rm-restore='trash-restore --trash-dir ~/.trash'
alias trash-empty='trash-empty --trash-dir ~/.trash'
EOF
                dialog --title "ntool-tui:tips" --msgbox "完成!重启termux以应用.下面是一些使用提示: \nrm-文件转移到~/.trash \nrl-显示回收站里的文件 \nrm-restore-选择要从回收站里恢复的文件 \ntrash-empty-清除回收站" 15 70
            fi
            ;;
        1)
            sed -i '/trash/d' ${PREFIX}/etc/profile
            dialog --title "ntool-tui:tips" --msgbox "完成!" 15 70
            tool_tui
            ;;
    esac
}

function tool_tui(){			#这里是其它工具-工具类页面的function
    TPC=$(dialog --output-fd 1 --title "ntool-tui:tool tui" --menu "选择一个以继续" 15 70 8 \
    "1" "ping" \
    "2" "ping6" \
    "3" "文件查找" \
    "4" "安装openjdk17" \
    "5" "ssh功能" \
    "6" "二维码功能" \
    "7" "rm防误删" \
    "00" "打开该项目地址(?)" \
    "0" "返回上一页")
    EXITSTATUS=$?
    if [ $EXITSTATUS != 0 ];then
        other_tool_tui
    fi
	case $TPC in
		0)
			other_tool_tui
			;;
		00)
            print_author ntool nya
			am start -a android.intent.action.VIEW -d ${GHREPO} > /dev/null 2>&1
			;;

		1)
			if command -v ping > /dev/null 2>&1;then
                 ip=$(dialog --output-fd 1 --title "ntool-tui:ping-ip" --inputbox "输入要进行ping的IP/域名(必填)"15 70)
                 time=$(dialog --output-fd 1 --title "ntool-tui:ping-time" --inputbox "输入要ping的次数(选填)" 15 70)
                 speed=$(dialog --output-fd 1 --title "ntool-tui:ping-speed" --inputbox "输入ping的速度(选填)（以秒为单位，省略符号，无root最快0.2）" 15 70)
                 size=$(dialog --output-fd 1 --title "ntool-tui:ping-packet-szie" --inputbox "输入ping包大小(选填)(以字节为单位，最大65507)" 15 70)
                if [ -z $ip ] || [ -z $time ] || [ -z $speed ] || [ -z $size ];then
                    bad_empty_input
                    tool_tui
                else 
                    echo -e "${BLUE}start ping${RESET}"
    				ping -i ${speed} -c${times} -s ${size} ${ip}
	    			echo -e "${GREEN}stop ping${RESET}"
                fi
			else
				echo "未安装ping，正在安装..."
				pkg install -y termux-tools
				tool_tui
			fi
			;;
		2)
			if command -v ping6 > /dev/null;then
                 ip=$(dialog --output-fd 1 --title "ntool-tui:ping6-ip" --inputbox "输入要进行ping6的IP/域名(必填)"15 70)
                 time=$(dialog --output-fd 1 --title "ntool-tui:ping6-time" --inputbox "输入要ping6的次数(选填)" 15 70)
                 speed=$(dialog --output-fd 1 --title "ntool-tui:ping6-speed" --inputbox "输入ping6的速度(选填)（以秒为单位，省略符号，无root最快0.2）" 15 70)
                 size=$(dialog --output-fd 1 --title "ntool-tui:ping6-packet-szie" --inputbox "输入ping6包大小(选填)(以字节为单位，最大65507)" 15 70)
                if [ -z $ip ] || [ -z $time ] || [ -z $speed ] || [ -z $size ];then
                    bad_empty_input
                    tool_tui
                else
                    echo -e "${BLUE}start ping${RESET}"
                    ping6 -i ${speed} -c${time} -s ${size} ${ip}
                    echo -e "${GREEN}stop ping${RESET}"
                fi
			else
				echo "ping6未安装,正在安装..."
				pkg install -y termux-tools
				tool_tui
			fi
			;;
		3)
             filename=$(dialog --output-fd 1 --title "ntool-tui:find file" --inputbox "输入你要搜索的文件:" 15 70)
             filepath=$(dialog --output-fd 1 --title "ntool-tui:find file" --inputbox "输入你要搜索的目录:" 15 70)
            if [ -z $filename ] || [ -z $filepath ];then
                bad_empty_input
            fi
			echo -e "${BLUE}搜索中${RESET}"
            echo -e "可能${RED}较慢${RESET},请${GREEN}耐心等待${RESET}"
            echo -e "${BLUE}搜索中${RESET}"
            result=$(find -name ${filename} ${filepath})
            echo "${result}" > ~/filesearchresult
            echo -e "${GREEN}完成${RESET}"
            echo -e "${BLUE}结果:${RESET}\n${result}"
            echo -e "${GREEN}复制一份于~/filesearchresult"
            read -p "按回车继续"
            echo -e "$RESET"
            tool_tui
			;;
		4)
			echo "只支持openjdk17"
			read -p "按任意键以继续"	#我好水啊（）
			pkg install -y openjdk-17
			echo "安装完成"
			;;
		5)
			ssh_check_install
			;;
		6)
            command -v qrencode 
            EXITSTATUS=$?
            if [ ${EXITSTATUS} != 0 ];then
                pkg install -y libqrencode zbar
                qrcode_tui
            else
                qrcode_tui
            fi
			;;
        7)
            rm_to_trash
            ;;
	esac
    exit 0
}

function web_tui(){				#这里是其他功能-网络类页面function
	#echo "这里是最水的页面（doge）"
    webc=$(dialog --output-fd 1 --title "ntool-tui:web tui" --menu "选择一个以继续" 15 70 8 \
    "1" "安装Nginx" \
    "2" "安装Apache2" \
    "3" "安装php环境" \
    "4" "安装MySQL(mariadb)" \
    "0" "返回上一页")
    EXITSTATUS=$?
	if [ $EXITSTATUS != 0 ];then
        other_tool_tui
    fi
	case $webc in
		0)
			other_tool_tui
			;;
		1)
			pkg install -y nginx
			echo "done"
			;;
		2)
			pkg install -y apache2
			echo "done"
			;;
		3)
			pkg install -y php
			echo "done"
			;;
		4)
			pkg install -y mariadb
			echo "done"
			;;
	esac
}

######main tui
function termux_main_tui(){
    MAINCHOICE=$(dialog --output-fd 1 --title "ntool-tui:main tui" --menu "你的系统为:${OS}\n选择一个以继续" 15 70 8  \
    "1" "已烂尾的容器功能" \
    "2" "其它功能" \
    "3" "备份功能" \
    "4" "计算圆周率(好水)" \
    "5" "一言" \
    "6" "LSPatch/XPatch功能" \
    "7" "ntafetch-使用ntafetch作为motd(测试)" \
    "8" "反映一个BUG" \
    "9" "卸载 ntool" \
    "00" "更新" \
    "0" "退出")
    EXITSTATUS=$?
    if [ $EXITSTATUS != 0 ];then
        echo -e "${BLUE}b${GREEN}y${YELLOW}e${RESET}"
        exit 0
    fi
    case $MAINCHOICE in 
        00)
	        check_and_update
        	;;
        0)
            echo -e "${BLUE}b${GREEN}y${YELLOW}e${RESET}"
            exit 0
            ;;
        1)
            source ${PREFIX}/lib/ntool/container/container.sh
            container_tui
            ;;
        2)
            other_tool_tui
            ;;
        3)
            backup_tui
            ;;
        4)
            if command -v bc > /dev/null;then
                 BC=$(dialog --output-fd 1 --title "ntool-tui:bc PI" --inputbox "输入计算位数    越往后面算的越慢" 15 70)
                EXITSTATUS=$?
                if [ $EXITSTATUS != 0 ];then
                    termux_main_tui
                fi
                echo -e "${GREEN}请耐心等待...${RESET}"
                echo "计算开始时间:$(date '+%Y-%m-%d %H:%M:%S.%N')" > ${HOME}/pi.txt
                echo "scale=${BC}; 4*a(1)" | bc -l -q >> ${HOME}/pi.txt
                echo "计算结束时间:$(date '+%Y-%m-%d %H:%M:%S.%N')" >> ${HOME}/pi.txt
                dialog --title "ntool-tui:success" --textbox "${HOME}/pi.txt" 20 80
                termux_main_tui
            else
                echo -e "${BLUE}正在安装bc计算器...${RESET}"
                pkg install -y bc
                echo -e ${GREEN}
                read -p "按回车返回"
                echo -e ${RESET}
                termux_main_tui
            fi
            ;;
        5)
            dialog --title "ntool-一言" --msgbox "$(curl https://v1.hitokoto.cn/?encode=text 2>/dev/null)" 15 70
            termux_main_tui
            ;;
        6)
            patch_framework_choose
            ;;
        7)
            check_if_not_android_warning
            function ntafetch_install(){
                wget https://raw.githubusercontent.com/nya-main/ntafetch/main/ntafetch -O ${PREFIX}/bin/ntafetch
                chmod +x ${PREFIX}/bin/ntafetch
                mv $PREFIX/etc/motd ${PREFIX}/etc/motd.bak > /dev/null 2>&1
            }
            if (dialog --title "ntool-tui:developing action" --defaultno --yesno "ntafetch由无数个echo -e组成\n写这个的主要原因是因为termux自带motd过于臃肿\n并不推荐使用，因为没有经过足够的测试" 15 70);then
                 ISINSTALLED="$(cat ${PREFIX}/etc/termux-login.sh | grep ntafetch)"
                if [ ! -z "$ISINSTALLED" ];then
                    if (dialog --title "ntool-tui:WARNING" --defaultno --yesno "你已经安装过ntafetch了\n你确定要重装吗?" 15 70);then
                        ntafetch_install
                    else
                        termux_main_tui
                    fi
                else
                    ntafetch_install
                    echo "ntafetch" >> ${PREFIX}/etc/termux-login.sh
                fi
            else
                termux_main_tui
            fi
            termux_main_tui
            ;;
        8)
            dialog --title "ntool-tui:report" --yes-label "GitHub" --no-label "Blog" --yesno "你可以到ntool项目下提出issue \n或者到博客的关于页找我 \n我也会看的" 15 70
            EXITSTATUS=$?
            if [ ${EXITSTATUS} = 255 ];then
                termux_main_tui
            elif [ ${EXITSTATUS} = 0 ];then
                am start -a android.intent.action.VIEW -d ${GHREPO} > /dev/null 2>&1
            elif [ ${EXITSTATUS} = 1 ];then
                dialog --title "ntool-tui:give me the money!" --yes-label "好的" --no-label "可以" --yesno "博客由于经营不善,倒闭了qwq\n我需要你的帮助(⁠≧⁠▽⁠≦⁠)\n你愿意v我50嘛?" 0 0
                EXITSTATUS=$?
                if [ ${EXITSTATUS} = 255 ];then
                    echo -e "哼,连50都不愿意给我!!\n再也不见qwq"
                    exit 123
                else
                    echo -e "${CYAN}好耶!${RESET}"
                    read -p "press enter please"
                    termux_main_tui
                fi
            fi
            ;;
        9)
            source "${NTOOLLIB}/basic/uninstall.sh"
            uninstall_ntool
            ;;
    esac
    exit 0
}
