#!/usr/bin/env bash
#there is nothing in this file.
#all scripts are here:
#${PREFIX}lib/ntool/
#so this is just an start script
#:D
if [[ "$(uname -o)" == "Android" ]]; then
    source "${HOME}/.local/ntool/basic/preload.sh"
    start $*
else
    source "${HOME}/.local/ntool/linux/preload.sh"
fi

#EOF