#!/data/data/com.termux/files/usr/bin/bash
#ntool启动脚本
unset LD_PRELOAD
COMMAND="proot"
COMMAND+=" --link2symlink"
COMMAND+=" -0"
COMMAND+=" -r ~/.ntool/ubuntu-fs"
COMMAND+=" -b /dev"
COMMAND+=" -b /sys"
COMMAND+=" -b proc"
#不建议直接挂载sdcard
#COMMAND+=" -b /sdcard"
#下面仅挂载HOME
COMMAND+=" -b /data/data/com.termux/files/home:/root"
COMMAND+=" -w root"
COMMAND+=" /usr/bin/env -i"
COMMAND+=" HOME=/root"
COMMAND+=" PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games"
COMMAND+=" TERM=xterm-256color"
COMMAND+=" LANG=C.UTF-8"
COMMAND+=" /bin/bash -l"
